basePath: /
definitions:
  internal_gateway_handler.APIError:
    properties:
      error:
        example: error message
        type: string
    type: object
  phoenix_processor_pkg_pb.ActivateCARequest:
    properties:
      ca_passwd:
        description: CA password.
        type: string
      ca_path:
        description: File path to CA.
        type: string
      person_id:
        description: Holder's person ID.
        type: string
    type: object
  phoenix_processor_pkg_pb.ActivateCAResponse:
    properties:
      success:
        type: boolean
    type: object
  phoenix_processor_pkg_pb.GetCAExpireTimeRequest:
    properties:
      person_id:
        type: string
    type: object
  phoenix_processor_pkg_pb.GetCAExpireTimeResponse:
    properties:
      expire_time:
        type: string
    type: object
  phoenix_processor_pkg_pb.LogoutResponse:
    properties:
      success:
        description: True if logout was successful.
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: REST API Gateway for Shioaji Trading Provider.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Phoenix API
  version: "1.0"
paths:
  /api/v1/ca/activate:
    post:
      consumes:
      - application/json
      description: Activate the Certificate Authority for the user
      parameters:
      - description: CA Activation Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/phoenix_processor_pkg_pb.ActivateCARequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/phoenix_processor_pkg_pb.ActivateCAResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_gateway_handler.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_gateway_handler.APIError'
      security:
      - Bearer: []
      summary: Activate CA
      tags:
      - Auth
  /api/v1/ca/expire:
    get:
      consumes:
      - application/json
      description: Retrieve the expiration time of the user's Certificate Authority
      parameters:
      - description: CA Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/phoenix_processor_pkg_pb.GetCAExpireTimeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/phoenix_processor_pkg_pb.GetCAExpireTimeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_gateway_handler.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_gateway_handler.APIError'
      security:
      - Bearer: []
      summary: Get CA Expire Time
      tags:
      - Auth
  /api/v1/logout:
    post:
      description: Invalidate the session (placeholder for now)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/phoenix_processor_pkg_pb.LogoutResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_gateway_handler.APIError'
      security:
      - Bearer: []
      summary: User Logout
      tags:
      - Auth
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and then your token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
